routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', ['uses' => 'HomeController@index'])->name('index');
Route::get('/contact-us', ['uses' => 'HomeController@contactForm'])->name('contact-us.form');
Route::post('/contact-us', ['uses' => 'HomeController@contact'])->name('contact-us.store');
Route::get('/category/{slug}', ['uses' => 'CategoryController@show'])->name('category.show');
Route::post('/category', ['uses' => 'CategoryController@posts'])->name('category.posts');
Route::get('/categories', ['uses' => 'CategoryController@index'])->name('categories');
Route::get('/video/{slug}', ['uses' => 'HomeController@show'])->name('posts.show');
Route::post('/subscribe', ['uses' => 'HomeController@subscribe'])->name('subscribe');
Route::get('/page/{slug}', ['uses' => 'PageController@show'])->name('pages.show');
Route::get('/video/{slug}', ['uses' => 'PostController@show'])->name('posts.show');
Route::post('/season', ['uses' => 'SeasonController@posts'])->name('season.posts');
Route::get('/season/{id}',['uses' => 'SeasonController@show'])->name('season.show');
Route::get('/regenerate_media/{offset?}', 'MediaRegeneratController@regenerate_media')->name('media.cron');

app/Models/Page.php
<?php

namespace App\Models;

use Dot\Pages\Models\Page as Model;

class Page extends Model
{
    /**
     * Path attribute
     * @return string
     */
    public function getPathAttribute()
    {
        return route('pages.show', ['slug' => $this->slug]);
    }
}

resources/views/categories.blade.php
@extends('layouts.app')
@section('title','Dotinsider | القنوات')
@section('content')
    <section class="bg-section full-height">
        <div class="container">
            @include('layouts.partials.header')
            <div class="categories-channels to-hide">
                <p class="title-section main-title-font  zigzag d-inline-block">القنوات</p>
                <div class="channels  d-inline-block">
                    @foreach($categories as $category)
                        <div class="img-channel d-inline-block">
                            <a href="{{$category->path}}" class="channel-card"><img
                                        src="{{thumbnail($category->image->path, 'cat-footer-logo')}}" alt="#"></a>
                        </div>
                    @endforeach
                    <div class="insert-more" style="display: none;"></div>
                    @if(count($categories) == 12)
                        <div class="more">
                            <a href="javascript:void(0)" class="btn-more">المزيد <i class="icon-arrow-down"></i></a>
                        </div>
                    @endif
                </div>
            </div>
        </div>
        <div class="bg-circle">
            <img src="{{assets('assets')}}/img/Elements-Circle.png" alt="">
        </div>
        <div class="bg-cuboid">
            <img src="{{assets('assets')}}/img/Elements-Cuboid.png" alt="">
        </div>
        <div class="bg-triangle-up">
            <img src="{{assets('assets')}}/img/Elements-Triangle-2.png" alt="">
        </div>
        <div class="bg-group">
            <img src="{{assets('assets')}}/img/absoluteGroup.png" alt="">
        </div>
    </section>
    @push('scripts')
        <script>
            $(function () {
                offset = 12
                $('.btn-more').on('click', function (e) {
                    e.preventDefault();
                    // $('.more').hide()
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });
                    $.ajax({
                        type: "get",
                        url: "{{route('categories')}}",
                        data: {'offset': offset, 'limit': 12},
                        async: false,
                        success: function (data) {
                            if (data.count > 0) {
                                var html="";
                                for(i = 0; i < data.count; i++){
                                    html +=
                                '<div class="img-channel d-inline-block"><a href="'+data.cats[i].path+'" class="channel-card">"'+
                                    '<img src="'+data.cats[i].thumb+'" alt="#"></a> </div>';
                                }
                                $(html).insertBefore('.insert-more');
                                offset += data.count;
                            }
                            if(data.count < 12)
                                $('.more').remove()
                            else
                                $('.more').show()
                        }
                    })
                });
            })
        </script>
    @endpush
@endsection
@section('footer')
@endsection

resources/views/category.blade.php
@extends('layouts.app')
@section('title','Dotinsider | '.$category->name)
@section('content')
    <section class="bg-section category">
        <div class="container">
            @include('layouts.partials.header')
            <div class="channel to-hide">
                <div class="image">
                    <img src="{{thumbnail($category->image->path, 'cat-footer-logo')}}" alt="">
                </div>
                <div class="text">
                    <p class="main-title-font zigzag">{{$category->name}}</p>
                    <p class="description">{{$category->excerpt}}</p>
                    <div class="social">
                        <a href="{{option('facebook_page')}}" target="_blank">FACEBOOK</a>
                        <a href="{{option('twitter_page')}}" target="_blank">TWITTER</a>
                        <a href="{{option('youtube_page')}}" target="_blank">YOUTUBE</a>
                    </div>
                </div>
            </div>
            <div class="slider-1 rtl-container rtl right-mrg to-hide">
                <div class="swiper-container video-container" dir="ltr">
                    <div class="swiper-wrapper" id="cat-slider">
                        <?php $x=0; ?>
                        @foreach($category->category_feature as $slider)
                            <div class="swiper-slide">
                                <img src="{{thumbnail($category->category_image[$x]->path,'main-slider')}}">
                                <div class="over-element bg-h">
                                    <a href="javascript:void(0)" class="open"
                                       data-poster="{{thumbnail($slider->provider_image, 'video-details')}}"
                                       data-link="{{$slider->path}}">
                                        <i class="icon-play-icon"></i>
                                    </a>
                                </div>
                            </div>
                                <?php ++$x; ?>
                        @endforeach
                    </div>
                </div>
                <div class="triangle">
                    <img src="{{assets('assets')}}/img/triangle.png" alt="">
                </div>

                <div class="swiper-button-prev">
                    <i class="icon-arrow-left"></i>
                </div>
                <div class="swiper-button-next">
                    <i class="icon-arrow-right"></i>
                </div>
            </div>
            <div class="slider-2 cat-slider to-hide">
                <div class="swiper-container">
                    <div class="swiper-wrapper">
                        @foreach($seasons as $season)
                            <div class="swiper-slide">
                                <a href="javascript:void(0)" data-id="{{$season->id}}"
                                   class="main-title-font season-click">{{$season->name}}</a>
                                <p>{{$season->count}} Episodes</p>
                            </div>
                        @endforeach
                    </div>
                    <div class="swiper-button-prev">
                        <i class="icon-arrow-left"></i>
                    </div>
                    <div class="swiper-button-next">
                        <i class="icon-arrow-right"></i>
                    </div>
                </div>
            </div>
            <div class="bg-v to-hide">
                <a href="#" class="read">اقرأ المزيد</a>
                <a href="#" class="see">الكل</a>
            </div>
        </div>
        <div class="bg-circle">
            <img src="{{assets('assets')}}/img/Elements-Circle.png" alt="">
        </div>
        <div class="bg-cuboid">
            <img src="{{assets('assets')}}/img/Elements-Cuboid.png" alt="">
        </div>
        <div class="bg-group">
            <img src="{{assets('assets')}}/img/absoluteGroup.png" alt="">
        </div>
    </section>
    <section class="section-padding">
        <div class="container">
            <p class="title-section main-title-font black-color zigzag title-video">أخر الفيديوهات</p>
            <div class="cards">
                @include('extensions.index-videos', ['posts', $posts])
                <div class="insert-more" style="display: none;"></div>
            </div>
            @if(count($posts) == 12)
                <div class="more">
                    <a href="javascript:void(0)" class="btn-more">MORE <i class="icon-arrow-down"></i></a>
                </div>
            @endif
        </div>
    </section>
    @include('extensions.subscribe')
    @push('scripts')
        <script>
            $(function () {
                offset = 12
                $('.btn-more').on('click', function (e) {
                    e.preventDefault();
                    // $('.more').hide()
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });
                    $.ajax({
                        type: "get",
                        url: "{{route('category.show', $category->slug)}}",
                        data: {'offset': offset, 'limit': 12},
                        async: false,
                        success: function (data) {
                            if (data.count > 0) {
                                $(data.view).insertBefore('.insert-more');
                                $('.card').each(function () {
                                    if ($(this).isInViewport()) {
                                        $(this).css({
                                            opacity: '1',
                                            transform: 'translateY(-10px)'
                                        });
                                    }
                                });
                                offset += data.count;
                            }
                            $('.more').show()
                        }
                    })
                });
                $('.season-click').on('click', function (e) {
                    e.preventDefault();
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });
                    $.ajax({
                        type: "post",
                        url: "{{route('season.posts')}}",
                        data: {season_id: $(this).data('id'), cat: true},
                        success: function (data) {
                            //$('#cat-slider').html(data.view)
                          /*  var mySwiper = new Swiper('.slider-1 .swiper-container', {
                                speed: 400,
                                autoplay: {
                                    delay: 5000,
                                },
                                navigation: {
                                    nextEl: '.slider-1 .swiper-button-next',
                                    prevEl: '.slider-1 .swiper-button-prev',
                                },
                            });*/

                            $('.cards').html(data.view);
                            $('.card').each(function () {
                                if ($(this).isInViewport()) {
                                    $(this).css({
                                        opacity: '1',
                                        transform: 'translateY(-10px)'
                                    });
                                }
                            });
                        }
                    })
                })
            })

        </script>
    @endpush

@endsection

resources/views/index.blade.php
@extends('layouts.app')
@section('title','Dotinsider')
@section('content')
    <section class="bg-section category home">
        <div class="container">
            @include('layouts.partials.header')
            <div class="slider-2 to-hide">

                <div class="swiper-container">
                    <div class="swiper-wrapper">
                        @foreach($cats as $cat)
                            <div class="swiper-slide" data-id="{{$cat->id}}">
                                <a href="{{ route('category.show', ['slug' => $cat->slug]) }}"><img
                                            src="{{thumbnail($cat->image->path, 'cat-footer-logo')}}" alt=""></a>
                            </div>
                        @endforeach
                    </div>
                    <div class="swiper-button-prev">
                        <i class="icon-arrow-left"></i>
                    </div>
                    <div class="swiper-button-next">
                        <i class="icon-arrow-right"></i>
                    </div>
                </div>
            </div>

            <div class="slider-1 rtl-container rtl right-mrg to-hide">
                <div class="swiper-container video-container" dir="ltr">
                    <div class="swiper-wrapper" id="cat-slider">
                        @foreach($posts_slider as $post)
                            <div class="swiper-slide" data-url="{{$post->category->path}}">
                                <div class="slide-content">
                                    <img src="{{thumbnail($post->image->path, 'main-slider')}}">
                                    <div class="over-element bg-h">
                                        <a href="javascript:void(0)" class="open"
                                           data-poster="{{thumbnail($post->image->path, 'video-details')}}"
                                           data-link="{{$post->media->path}}">
                                            <i class="icon-play-icon"></i>
                                        </a>
                                    </div>
                                </div>
                                <div class="channel to-hide">
                                    <div class="text">
                                        <p class="main-title-font zigzag">{{$post->category->name}}</p>
                                        <p class="description">{{$post->title}}</p>
                                        <div class="social" data-youtube="{{$post->media->path}}"
                                             data-url="{{$post->path}}"
                                             data-title="{!! $post->title !!}">
                                            <a href="javascript:void(0)" class="shareBtn facebook">FACEBOOK</a>
                                            <a href="javascript:void(0)" class="shareBtn twitter">TWITTER</a>
                                            <a href="javascript:void(0)" class="shareBtn youtube">YOUTUBE</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>

                </div>
                <div class="triangle">
                    <img src="{{assets('assets')}}/img/triangle.png" alt="">
                </div>
                <div class="swiper-button-prev">
                    <i class="icon-arrow-left"></i>
                </div>
                <div class="swiper-button-next">
                    <i class="icon-arrow-right"></i>
                </div>

            </div>
            <div class="bg-v to-hide">
                <a href="{{route('categories')}}" class="read">كل القنوات</a>
                <a href="{{$posts_slider ? $posts_slider[0]->category->path : '#'}}" class="see" id="read-more">انتقل
                    للأسفل </a>
            </div>
            <div class="bg-circle">
                <img src="{{assets('assets')}}/img/Elements-Circle.png" alt="">
            </div>
            <div class="bg-cuboid">
                <img src="{{assets('assets')}}/img/Elements-Cuboid.png" alt="">
            </div>
            <div class="bg-group">
                <img src="{{assets('assets')}}/img/absoluteGroup.png" alt="">
            </div>
        </div>
    </section>
    <section class="section-padding">
        <div class="container">
            <p class="title-section main-title-font black-color zigzag title-video">أخر الفيديوهات</p>
            <div class="cards">
                @include('extensions.index-videos', ['posts'=>$main_posts])
                <div class="insert-more" style="display: none;"></div>
            </div>
            @if(count($main_posts) == 12)
                <div class="more">
                    <a href="javascript:void(0)" class="btn-more">المزيد <i class="icon-arrow-down"></i></a>
                </div>
            @endif
        </div>
    </section>

    @include('extensions.subscribe')

    @push('scripts')
        <script>
            $(function () {
                var catCount = "{{count($cats) >= 4 ? 4 :count($cats)  }}";
                var mySwiper = new Swiper('.home .slider-2 .swiper-container', {
                    speed: 400,
                    loop: true,
                    slidesPerView: catCount,
                    slideToClickedSlide: false,
                    /*autoplay: {
                        delay: 5000,
                        disableOnInteraction: false
                    },*/
                    navigation: {
                        nextEl: '.slider-2 .swiper-button-next',
                        prevEl: '.slider-2 .swiper-button-prev',
                    },
                    breakpoints: {
                        1024: {
                            slidesPerView: catCount,
                        },
                        786: {
                            slidesPerView: catCount,
                            navigation: {
                                nextEl: null,
                                prevEl: null
                            }
                        },
                    },
                });
                /*
                 document.querySelector('.slider-1 .swiper-container').swiper.on('slideChange', function () {
                     $('#read-more').attr('href', $('#cat-slider').find('.swiper-slide-active').data('url'));
                 });
                 mySwiper.on('slideChange', function () {
                     var id = $('.slider-2').find('.swiper-slide-active').data('id');
                     $.ajaxSetup({
                         headers: {
                             'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                         }
                     });
                     $.ajax({
                         type: "post",
                         url: "{{route('category.posts')}}",
                        data: {category_id: id},
                        success: function (data) {
                            destroy = document.querySelector('.slider-1 .swiper-container').swiper;
                            destroy.destroy();
                            $('#cat-slider').html(data.view)
                            var videoSwiper = new Swiper('.slider-1 .swiper-container', {
                                speed: 400,
                                autoplay: {
                                    delay: 5000,
                                    disableOnInteraction: false
                                },
                                navigation: {
                                    nextEl: '.slider-1 .swiper-button-next',
                                    prevEl: '.slider-1 .swiper-button-prev',
                                },
                            });
                            readURL = $('#cat-slider').find('.swiper-slide-active').data('url');
                            $('#read-more').attr('href', readURL);
                            videoSwiper.on('slideChange', function () {
                                $('#read-more').attr('href', readURL);
                            });
                        }
                    })
                });
                */
                offset = 12
                $('.btn-more').on('click', function (e) {
                    e.preventDefault();
                    $('.more').hide()
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });
                    $.ajax({
                        type: "get",
                        url: "{{route('index')}}",
                        data: {'offset': offset, 'limit': 12},
                        async: false,
                        success: function (data) {
                            if (data.count > 0) {
                                $(data.view).insertBefore('.insert-more');
                                $('.card').each(function () {
                                    if ($(this).isInViewport()) {
                                        $(this).css({
                                            opacity: '1',
                                            transform: 'translateY(-10px)'
                                        });
                                    }
                                });
                                offset += data.count;
                            }
                            if (data.count < 12)
                                $('.more').remove();
                            else
                                $('.more').show()
                        }
                    })
                });
            })
        </script>
    @endpush
@endsection

resources/views/page-details.blade.php
@extends('layouts.app')
@section('title','Dotinsider | '. $page->title)
@section('content')
    <section class="bg-section about">
        <div class="container">
            @include('layouts.partials.header')
            <div class="about-us to-hide">
                <div>
                    <div class="width-25">
                        <p class="zigzag main-title-font">{{$page->title}}</p>
                    </div>
                    <div class="width-75">
                        <p class="main-title-font smaller">
                            {{$page->excerpt}}
                        </p>
                        <span>
                            {{ strip_tags($page->content)}}
                        </span>

                        <div class="channels-logo">
                            <?php $i = 1;?>
                            @foreach($cats as $cat)
                                <a href="javascript:void(0)" id="channel{{$i}}" @if($i == 1)class="active"@endif>
                                    <img src="{{thumbnail($cat->image->path, 'cat-footer-logo')}}" alt="">
                                </a>
                                <?php $i++;?>
                            @endforeach
                        </div>

                        <div class="related-to-channel">
                            <?php $i = 1;?>
                            @foreach($cats as $cat)
                                <div data-index="channel{{$i}}">
                                    <p class="main-title-font zigzag smaller">
                                        {{$cat->name}}
                                    </p>
                                    <p>
                                        {{$cat->excerpt}}
                                    </p>
                                    <ul class="social-icons">
                                        <li><a href="#" target="_blank">FACEBOOK</a></li>
                                        <li><a href="#" target="_blank">TWITTER</a></li>
                                        <li><a href="#" target="_blank">YOUTUBE</a></li>
                                    </ul>
                                </div>
                                <?php $i++;?>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="bg-circle">
            <img src="{{assets('assets')}}/img/Elements-Circle.png" alt="">
        </div>
        <div class="bg-cuboid">
            <img src="{{assets('assets')}}/img/Elements-Cuboid.png" alt="">
        </div>
        <div class="bg-triangle-up">
            <img src="{{assets('assets')}}/img/Elements-Triangle-2.png" alt="">
        </div>
        <div class="bg-group">
            <img src="{{assets('assets')}}/img/absoluteGroup.png" alt="">
        </div>
    </section>
@endsection
@section('footer')
@endsection

resources/views/post.blade.php
@extends('layouts.app')
@section('meta')
    @include('extensions.meta',['post'=>$post])
@endsection
@section('title','Dotinsider | '.$post->title)
@section('content')
    <section class="bg-section video-details">
        <div class="container">
            @include('layouts.partials.header')
            <div class="rtl-container full-width to-hide">
                <div class="rtl right-mrg">
                    <div class="video-container">
                        <img src="{{thumbnail($post->image->path, 'video-details')}}">
                        <div class="over-element bg-h">
                            <a href="javascript:void(0)" class="open" data-poster="{{thumbnail($post->image->path, 'video-details')}}" data-link="{{$post->media->path}}">
                                <i class="icon-play-icon"></i>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="back-home" id="scroll">
                    <a href="javascript:void(0)">
                        أكتشف الأن
                        <i class="icon-arrow-right"></i>
                    </a>
                </div>

            </div>
            <div class="details-container to-hide mb-126">
                <a href="{{$post->category->path}}" class="image"><img src="{{assets('assets')}}/img/in-90.png" alt=""></a>
                <a href="javascript:void(0)" class="title">
                   {{$post->title}}
                </a>
                <div class="back-home">
                    <a href="{{route('index')}}">
                        الرجوع الى الرئيسية
                        <i class="icon-arrow-left"></i>

                    </a>
                </div>
            </div>
        </div>
        <div class="bg-circle">
            <img src="{{assets('assets')}}/img/Elements-Circle.png" alt="">
        </div>
        <div class="bg-cuboid">
            <img src="{{assets('assets')}}/img/Elements-Cuboid.png" alt="">
        </div>
        <div class="bg-group">
            <img src="{{assets('assets')}}/img/absoluteGroup.png" alt="">
        </div>
    </section>
    <section class="section-padding">
        <div class="container">
            <p class="title-section main-title-font title-video black-color zigzag">فيديوهات متعلقة</p>
            <div class="cards">
               @include('extensions.index-videos', ['posts' => $related_posts])
                <div class="insert-more" style="display: none;"></div>
            </div>
            @if(count($related_posts) == 12)
                <div class="more">
                    <a href="javascript:void(0)" class="btn-more">المزيد <i class="icon-arrow-down"></i></a>
                </div>
            @endif
        </div>
    </section>
    @include('extensions.subscribe')
    @push('scripts')
        <script>
            $(function () {

                offset = 12
                $('.btn-more').on('click', function (e) {
                    e.preventDefault();
                    $('.more').hide()
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });
                    $.ajax({
                        type: "get",
                        url: "{{route('posts.show', $post->slug)}}",
                        data: {'offset': offset, 'limit': 12},
                        async: false,
                        success: function (data) {
                            if (data.count > 0) {
                                $(data.view).insertBefore('.insert-more');
                                $('.card').each(function () {
                                    if ($(this).isInViewport()) {
                                        $(this).css({
                                            opacity: '1',
                                            transform: 'translateY(-10px)'
                                        });
                                    }
                                });
                                offset += data.count;
                            }
                            if (data.count < 12)
                                $('.more').remove();
                            else
                                $('.more').show()
                        }
                    })
                });
            })
        </script>
    @endpush
@endsection